controlplane $ cat clusterip.yaml
apiVersion: v1
kind: Service
metadata:
  name: webapp1-clusterip-svc
  labels:
    app: webapp1-clusterip
spec:
  ports:
  - port: 80
  selector:
    app: webapp1-clusterip
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp1-clusterip-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp1-clusterip
    spec:
      containers:
      - name: webapp1-clusterip-pod
        image: katacoda/docker-http-server:latest
        ports:
        - containerPort: 80
---
controlplane $


controlplane $ cat clusterip-target.yaml
apiVersion: v1
kind: Service
metadata:  name: webapp1-clusterip-targetport-svc
  labels:
    app: webapp1-clusterip-targetport
spec:  
  ports:
  - port: 8080
    targetPort: 80
  selector:    
    app: webapp1-clusterip-targetport
---
apiVersion: extensions/v1beta1
kind: Deploymentmetadata:
  name: webapp1-clusterip-targetport-deployment
spec:
  replicas: 2  template:
    metadata:
      labels:
        app: webapp1-clusterip-targetport
    spec:
      containers:
      - name: webapp1-clusterip-targetport-pod
        image: katacoda/docker-http-server:latest        
        ports:        
        - containerPort: 80
---
controlplane $


controlplane $ cat nodeport.yaml
apiVersion: v1
kind: Service
metadata:  
  name: webapp1-nodeport-svc
  labels:
    app: webapp1-nodeport
spec:  
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080  selector:
    app: webapp1-nodeport
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp1-nodeport-deployment
spec:  
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp1-nodeport
    spec:
      containers:
      - name: webapp1-nodeport-pod        
	    image: katacoda/docker-http-server:latest        
		ports:
        - containerPort: 80
---
controlplane $


controlplane $ cat externalip.yaml
apiVersion: v1
kind: Service
  metadata:
  name: webapp1-externalip-svc
  labels:
    app: webapp1-externalip
spec:
  ports:
  - port: 80
  externalIPs:  
  - 172.17.0.37
  selector:
    app: webapp1-externalip
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp1-externalip-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp1-externalip
    spec:
      containers:      
	  - name: webapp1-externalip-pod        
	    image: katacoda/docker-http-server:latest
        ports:
        - containerPort: 80
---
controlplane $


controlplane $ k get svc
NAME                               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
kubernetes                         ClusterIP   10.96.0.1        <none>        443/TCP        30m
webapp1-clusterip-svc              ClusterIP   10.106.78.126    <none>        80/TCP         27m
webapp1-clusterip-targetport-svc   ClusterIP   10.101.217.213   <none>        8080/TCP       18m
webapp1-externalip-svc             ClusterIP   10.103.122.133   172.17.0.37   80/TCP         2m21s
webapp1-nodeport-svc               NodePort    10.101.24.235    <none>        80:30080/TCP   13m
controlplane $ curl 10.106.78.126
<h1>This request was processed by host: webapp1-clusterip-deployment-669c7c65c4-5d4pr</h1>
controlplane $ curl 10.103.122.133
<h1>This request was processed by host: webapp1-externalip-deployment-6446b488f8-b747g</h1>
controlplane $ curl 10.101.24.235
<h1>This request was processed by host: webapp1-nodeport-deployment-677bd89b96-994nh</h1>
controlplane $ curl 10.101.24.235:30080
^C
controlplane $ curl 172.17.0.37:30080
<h1>This request was processed by host: webapp1-nodeport-deployment-677bd89b96-994nh</h1>
controlplane $ curl 172.17.0.37
<h1>This request was processed by host: webapp1-externalip-deployment-6446b488f8-b747g</h1>
controlplane $
