# tolerate all nodes.
spec:
  tolerations: 
  - effect: NoSchedule
    operator: Exists      
    
controlplane $ cat ds.yml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
      tolerations:
      - effect: NoSchedule
        operator: Exists
controlplane $

controlplane $ k get pods -o wide
NAME                     READY   STATUS    RESTARTS   AGE    IP           NODE           NOMINATED NODE   READINESS GATES
nginx-deployment-cvzzz   1/1     Running   0          101s   10.244.0.3   controlplane   <none>           <none>
nginx-deployment-gvfk5   1/1     Running   0          101s   10.244.1.4   node01         <none>           <none>
controlplane $

# the same but above easier    
tolerations:
- key: node-role.kubernetes.io/master
  effect: NoSchedule
    
# remove taint    
controlplane $ k taint node controlplane node-role.kubernetes.io/master:NoSchedule-
node/controlplane untainted
controlplane $

controlplane $ k taint node node01 node-role.kubernetes.io/node01:NoSchedule
node/node01 tainted
controlplane $ k describe node node01|grep -i taint
Taints:             node-role.kubernetes.io/node01:NoSchedule
controlplane $ k taint node node01 node-role.kubernetes.io/node01:NoSchedule-
node/node01 untainted
controlplane $
